name: Homebrew
on: [push, pull_request]
jobs:
  install:
    runs-on: macos-latest
    strategy:
      matrix:
        formula:
          - python@2.7
          - python@3.5
          - python@3.6
          - python@3.9
    steps:
      - uses: actions/checkout@v2

      - name: Audit ${{ matrix.formula }}
        run: brew audit --strict --online Formula/${{ matrix.formula }}.rb

      - name: Install ${{ matrix.formula }}
        run: brew install Formula/${{ matrix.formula }}.rb

      - name: Test ${{ matrix.formula }}
        run: brew test Formula/${{ matrix.formula }}.rb
